version: '2'
services:
  web:
#    build: .    # 
    image: "nginx:latest"
    ports:
      - "8080:80"
    volumes:
      - ./files/nginx.conf:/etc/nginx/nginx.conf
      - ./files/ssl:/etc/nginx/ssl
#  redis:
#    image: "redis:alpine"

